import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Nav from "./components/ui/Nav";
import Footer from "./components/ui/Footer";

const kumbh = Kumbh_Sans({
  variable: "--font-geist",
  subsets: ["latin"],
  weight: ["400"], 
});



export const metadata = {
  title: "Dubai By Flamur",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning={true} />
      <body
        className={`${kumbh.variable} antialiased min-h-screen flex flex-col`}
        suppressHydrationWarning={true}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </>
  );
}
