import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Nav from "./components/ui/Nav";
import Footer from "./components/ui/Footer";

const playfair = Playfair_Display({
  variable: "--font-geist",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} antialiased min-h-screen flex flex-col`}
      >
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
